add 2 example usage
FedericoTartarini/jsthermalcomfort pull request #111
Opened 2023-10-22 04:17 UTC by Ilite-Kiriya

2023-10-23 09:34 UTC, szaldivar requested changes

2023-10-23 09:34 UTC, szaldivar commented on docs/examples/calc_jos3.html
> +    import { JOS3 } from "../../src/models/JOS3.js";
import from CDN

2023-10-23 09:34 UTC, szaldivar commented on docs/examples/calc_jos3.html
> +    model.to_csv("jos3_output_example/jos3_example2 (all output).csv");
I think we can omit the csv part

2023-10-23 09:34 UTC, szaldivar commented on docs/examples/calc_jos3.html
> +    model.to_csv("jos3_output_example/jos3_example1 (default output).csv");
we can omit this

2023-10-23 09:34 UTC, szaldivar commented on docs/examples/jos3_output_example/human_subject_experiment_dataset.xlsx
we probably want to remove this

2023-10-23 09:58 UTC, szaldivar commented on docs/examples/calc_jos3.html
> +      model.body_names;
```suggestion
    model.body_names;
```
I want to test something

2024-04-23 23:28 UTC, FedericoTartarini commented
@szaldivar could you please, if you have time, review this pull request and merge it if you are happy with the code?

2024-04-24 08:16 UTC, szaldivar commented
> @szaldivar could you please, if you have time, review this pull request and merge it if you are happy with the code?

Hi @FedericoTartarini, sorry I have been super busy. Yes I will take a look, I will schedule some of my time next week to get this resolved

2024-04-24 08:18 UTC, szaldivar commented
> @szaldivar could you please, if you have time, review this pull request and merge it if you are happy with the code?

Actually this looks good, ticked

2024-04-24 08:18 UTC, merged

2024-04-25 23:22 UTC, FedericoTartarini commented
Thank you very much for working on this.