utci finished
FedericoTartarini/jsthermalcomfort pull request #80
Opened 2023-10-01 11:15 UTC by Ilite-Kiriya

2023-10-03 09:24 UTC, szaldivar requested changes

2023-10-03 09:24 UTC, szaldivar commented on src/models/utci.js
> +const stress_categories = {
Better to use an array and do a binary search over it. @YuchenMu had a similar implementation for this. you can talk with him in how to do this in a better way

2023-10-03 09:24 UTC, szaldivar commented on src/models/utci.js
> +    const tdb_valid = valid_range(tdb, [-50.0, 50.0]);
valid_range is for arrays, just do a normal `tdb >= -50.0 && tdb <=50.0` here

2023-10-03 09:24 UTC, szaldivar commented on src/models/utci.js
> +    for (let i = 0; i < utci_approx.length; i++) {
I think we have a `units_converter` for arrays

2023-10-03 09:24 UTC, szaldivar commented on src/models/utci.js
> +  const g = [
can you declare this outside the function since it is a constant so we don't allocate this memory every time

2023-10-03 09:24 UTC, szaldivar commented on src/models/utci.js
> +  g.map((_g, i) => {
do a for loop. map creates an array so if you don't need to create an array don't use map

2023-10-03 09:24 UTC, szaldivar commented on src/models/utci.js
> +// console.log(utci_array([25, 25], [27, 25], [1, 1], [50, 50], "si", true))
?

2023-10-03 09:24 UTC, szaldivar commented on src/utilities/utilities.js
> +  if (!Array.isArray(range)) {
don't do this, if you need a numeric comparison just do the numeric comparison

2023-10-03 11:07 UTC, Ilite-Kiriya commented on src/models/utci.js
> +// console.log(utci_array([25, 25], [27, 25], [1, 1], [50, 50], "si", true))
will delete it later

2023-10-07 11:47 UTC, szaldivar approved these changes

2023-10-07 11:47 UTC, merged