calc_pmv_ppd - examples and explanations
FedericoTartarini/jsthermalcomfort pull request #95
Opened 2023-10-09 10:19 UTC by Lu-Whale

finished calc_pmv_ppd, modified v_relative_array in utilities.js

2023-10-09 10:37 UTC, szaldivar commented
there are some parts that used `v_relative_array`, that is why the tests are failing, make sure to update them as well

2023-10-09 11:10 UTC, Lu-Whale commented
> there are some parts that used `v_relative_array`, that is why the tests are failing, make sure to update them as well

updated the related test

2023-10-10 09:33 UTC, szaldivar requested changes

2023-10-10 09:33 UTC, szaldivar commented on docs/examples/calc_pmv_ppd.js
> +const startAshrae = new Date().getTime();
use `performance.now()`

2023-10-10 09:44 UTC, Lu-Whale commented on docs/examples/calc_pmv_ppd.js
> +const startAshrae = new Date().getTime();
done

2023-10-10 09:46 UTC, szaldivar approved these changes

2023-10-10 09:47 UTC, merged